### ISSUE TITLE
support for sending a private message to a user who joins a specific channel

### ISSUE THREAD

**Issue by devth** [yetibot/yetibot#689]
Depends on:

- [x] #446 Enable enter/leave observers
- [x] #501 room-specific observers
- [x] #506 slack replyto (needs docs update)
- [x] #694 Enable template access to channel name and username in enter/leave observers

**Comment by devth** [comment]
@cvic all the issues this depends on have been fixed! Closing!
